// Auto-generated canister IDs - DO NOT EDIT MANUALLY
// Generated by simple_canister_manager.sh on Sun Aug 17 23:22:18 EDT 2025

export const CANISTER_IDS = {
  "AxiaSystem_backend": "uzt4z-lp777-77774-qaabq-cai"
,
  "admin2": "umunu-kh777-77774-qaaca-cai"
,
  "asset": "ulvla-h7777-77774-qaacq-cai"
,
  "asset_registry": "ucwa4-rx777-77774-qaada-cai"
,
  "escrow": "ufxgi-4p777-77774-qaadq-cai"
,
  "governance": "vizcg-th777-77774-qaaea-cai"
,
  "identity": "vpyes-67777-77774-qaaeq-cai"
,
  "nft": "vg3po-ix777-77774-qaafa-cai"
,
  "payment": "vb2j2-fp777-77774-qaafq-cai"
,
  "payment_monitoring": "vu5yx-eh777-77774-qaaga-cai"
,
  "payout": "vt46d-j7777-77774-qaagq-cai"
,
  "split_payment": "v27v7-7x777-77774-qaaha-cai"
,
  "namora_ai": "xsfk2-nx777-77774-qaala-cai"
,
  "subscriptions": "v56tl-sp777-77774-qaahq-cai"
,
  "token": "xad5d-bh777-77774-qaaia-cai"
,
  "treasury": "xhc3x-m7777-77774-qaaiq-cai"
,
  "user": "xobql-2x777-77774-qaaja-cai"
,
  "wallet": "xjaw7-xp777-77774-qaajq-cai"
};

// Individual canister exports for convenience
export const AXIASYSTEM_BACKEND_CANISTER_ID = "uzt4z-lp777-77774-qaabq-cai";
export const ADMIN2_CANISTER_ID = "umunu-kh777-77774-qaaca-cai";
export const ASSET_CANISTER_ID = "ulvla-h7777-77774-qaacq-cai";
export const ASSET_REGISTRY_CANISTER_ID = "ucwa4-rx777-77774-qaada-cai";
export const ESCROW_CANISTER_ID = "ufxgi-4p777-77774-qaadq-cai";
export const GOVERNANCE_CANISTER_ID = "vizcg-th777-77774-qaaea-cai";
export const IDENTITY_CANISTER_ID = "vpyes-67777-77774-qaaeq-cai";
export const NFT_CANISTER_ID = "vg3po-ix777-77774-qaafa-cai";
export const PAYMENT_CANISTER_ID = "vb2j2-fp777-77774-qaafq-cai";
export const PAYMENT_MONITORING_CANISTER_ID = "vu5yx-eh777-77774-qaaga-cai";
export const PAYOUT_CANISTER_ID = "vt46d-j7777-77774-qaagq-cai";
export const SPLIT_PAYMENT_CANISTER_ID = "v27v7-7x777-77774-qaaha-cai";
export const NAMORA_AI_CANISTER_ID = "xsfk2-nx777-77774-qaala-cai";
export const SUBSCRIPTIONS_CANISTER_ID = "v56tl-sp777-77774-qaahq-cai";
export const TOKEN_CANISTER_ID = "xad5d-bh777-77774-qaaia-cai";
export const TREASURY_CANISTER_ID = "xhc3x-m7777-77774-qaaiq-cai";
export const USER_CANISTER_ID = "xobql-2x777-77774-qaaja-cai";
export const WALLET_CANISTER_ID = "xjaw7-xp777-77774-qaajq-cai";

// Network detection helper
export const getCanisterIds = (network = 'local') => {
  return CANISTER_IDS;
};

// Environment detection
export const getCurrentNetwork = () => {
  if (typeof window !== 'undefined') {
    const hostname = window.location.hostname;
    if (hostname.includes('ic0.app') || hostname.includes('icp0.io')) return 'ic';
    if (hostname.includes('testnet')) return 'testnet';
    return 'local';
  }
  return 'local';
};
